module.exports = {
    analytics: require('./analytics'),
    apiKeys: require('./apiKeys'),
    assetFolders: require('./assetFolders'),
    assets: require('./assets'),
    authentication: require('./authentication'),
    commentProviders: require('./commentProviders'),
    comments: require('./comments'),
    editors: require('./editors'),
    groups: require('./groups'),
    locales: require('./locales'),
    loggers: require('./loggers'),
    navigation: require('./navigation'),
    pageHistory: require('./pageHistory'),
    pageLinks: require('./pageLinks'),
    pages: require('./pages'),
    renderers: require('./renderers'),
    searchEngines: require('./searchEngines'),
    settings: require('./settings'),
    storage: require('./storage'),
    tags: require('./tags'),
    userKeys: require('./userKeys'),
    users: require('./users')
}